import java.io.*;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hovan
 */
public class Client extends javax.swing.JFrame  {
    private Socket socket;
    private String sender;
    private String receiver = "";
    private BufferedReader br;
    private BufferedWriter bw;
    private DataInputStream dis;
    private DefaultListModel<String> modelList = new DefaultListModel<String>();
    private String nameDirectory = "";
    /**
     * Creates new form Client
     */
    
    public Client(String username, Socket socket){
        try{
            initComponents();
            this.sender = username;
            this.socket = socket;
            this.bw = new BufferedWriter(new OutputStreamWriter(this.socket.getOutputStream(),StandardCharsets.UTF_8));
            this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream(),StandardCharsets.UTF_8)) ;
            this.dis = new DataInputStream(this.socket.getInputStream());
            jLabel3.setText(this.sender);
            this.setResizable(false);
            this.setTitle("Ứng dụng chat chít");
        }
        catch(Exception e){
            System.out.println("Error:" + e);
        }
    }


    public void sendMessenge(String messenger) {
        try {
            bw.write(messenger);
            bw.newLine();
            bw.flush();
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChatArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Ứng dụng tán ngẫu");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Username:");
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chatting:");
        jPanel3.add(jLabel5);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("...");
        jPanel3.add(jLabel4);

        jChatArea.setColumns(20);
        jChatArea.setRows(5);
        jScrollPane1.setViewportView(jChatArea);

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Online:");

        jLabel7.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (receiver.equals("")) {
            JOptionPane.showMessageDialog(this,"Bạn nên chọn ai đó đê gửi file");
            return;
        }
        StringBuilder sb = new StringBuilder();
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Chọn file");
        int respone = fc.showOpenDialog(null);
        if(respone == JFileChooser.APPROVE_OPTION){
            java.io.File file = fc.getSelectedFile();
            String name = file.getName();

            try{
                DataOutputStream dos = new DataOutputStream(this.socket.getOutputStream());
                FileInputStream fis = new FileInputStream(file.getAbsoluteFile());
                byte[] filenameBytes = name.getBytes();


                byte[] fileContentBytes = new byte[(int) file.length()];
                fis.read(fileContentBytes);
                bw.write("CLIENT&FILE:" + receiver);
                bw.newLine();
                bw.flush();
                TimeUnit.SECONDS.sleep(1);
                
                dos.writeInt(filenameBytes.length);
                dos.write(filenameBytes);

                dos.writeInt(fileContentBytes.length);
                dos.write(fileContentBytes);
            }
            catch(Exception e){
                System.out.println("Error:" + e);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextField3.getText().isEmpty()) return;
        if (receiver.equals("")) {
            JOptionPane.showMessageDialog(this,"Bạn nên chọn ai đó đê chat");
            return;
        }
        try {
            bw.write(sender +": " + jTextField3.getText() + "&&CLIENTCHAT:" + receiver);
            bw.newLine();
            bw.flush();
            String messenge = sender + ": " + jTextField3.getText() +"\n";
            jChatArea.append(messenge);
            jTextField3.setText("");
        } catch (Exception e) {
            System.out.println("Error:" + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int index = jList1.locationToIndex(evt.getPoint());
            String receiver = modelList.getElementAt(index);
            if(receiver.equals(this.sender)){
                JOptionPane.showMessageDialog(this,"Bạn không chọn chính bản thân được");
            }
            else{
                this.receiver = receiver;
                jLabel4.setText(receiver);
                jChatArea.setText("");
                sendMessenge(this.sender+"-LOAD-FILE:"+nameDirectory+this.sender+"-"+receiver+".txt");
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        sendMessenge("CLIENT-OFF:"+this.sender);
    }//GEN-LAST:event_formWindowClosing
    
    public void receive(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                String msgFromChat;
                int flag = 0;
                while(!socket.isClosed()){
                    try{
                        if(flag == 1){
                            int fileNameLength = dis.readInt();
                            if(fileNameLength > 0){
                                byte[] fileNameBytes = new byte[fileNameLength];
                                dis.readFully(fileNameBytes,0,fileNameBytes.length);
                                String filename = new String(fileNameBytes);
                                int fileContentLength = dis.readInt();

                                if(fileContentLength > 0){
                                    byte[] fileContentBytes = new byte[fileContentLength];
                                    dis.readFully(fileContentBytes,0,fileContentLength);
                                    flag = 0;
                                    int dialogResult = JOptionPane.showConfirmDialog(null,
                                             "Bạn nhận được một file\n Bạn có muốn tải về","Thông Báo",
                                            JOptionPane.YES_NO_OPTION,
                                            JOptionPane.QUESTION_MESSAGE);
                                    if(dialogResult == JOptionPane.YES_OPTION){
                                        File fileToDownLoad = new File(filename);
                                        try{
                                            FileOutputStream fos = new FileOutputStream(fileToDownLoad);
                                            
                                            fos.write(fileContentBytes);
                                            JOptionPane.showMessageDialog(null,"Tải thành công");
                                            fos.close();
                                        }
                                        catch (IOException e){
                                            e.printStackTrace();
                                        }
                                    }
                                }
                            }
                        }
                        msgFromChat = br.readLine();
                        if(msgFromChat == null) return;
                        if(msgFromChat.contains("SERVER&FILE")) {
                            flag = 1;
                        }

                        if(msgFromChat.contains("SERVER-ADD:")){
                            String name = msgFromChat.substring(msgFromChat.indexOf(":")+1);
                            jList1.setModel(modelList);
                            TimeUnit.MILLISECONDS.sleep(100);
                            modelList.addElement(name);

                            jLabel7.setText(Integer.toString(modelList.getSize()));

                        }
                        else if(msgFromChat.contains("SERVER-REMOVE:")){
                            String name = msgFromChat.substring(msgFromChat.indexOf(":")+1);

                            jList1.setModel(modelList);
                            for(int i = 0;i < modelList.getSize();i++){
                                if(modelList.getElementAt(i).equals(name)){
                                    modelList.removeElementAt(i);
                                    break;
                                }
                            }
                            jLabel7.setText(Integer.toString(modelList.getSize()));

                        }
                        else if(msgFromChat.contains("LOADCHAT:")){
                            String msg = msgFromChat.substring(msgFromChat.indexOf(":")+1);
                            jChatArea.append(msg+"\n");
                        }
                        else if (msgFromChat.contains(":")){
                            String name = msgFromChat.substring(0,msgFromChat.indexOf(":"));
                            if(name.equals(receiver)){
                                jChatArea.append(msgFromChat + "\n");
                            }

                        }

                    }catch (Exception e){
                        System.out.println("Error:" + e);
                    }
                }
            }
        }).start();
    }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jChatArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
